# The Falco Authors
# DOCS latest: falco.org
# REPO: https://github.com/falcosecurity/cncf-green-review-testing
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: falco-cncf-green-review-testing
  namespace: flux-system
spec:
  interval: 6h
  ref:
    branch: main
  url: https://github.com/falcosecurity/cncf-green-review-testing
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: falco-cncf-green-review-testing
  namespace: falco
spec:
  interval: 6h
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: falco-cncf-green-review-testing
  targetNamespace: falco
  timeout: 3m0s
  wait: true
