---
####################################################################
# Add custom resources which are not covered by view clusterrole
####################################################################
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crole-customresources-readyonly
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-account
  namespace: kube-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crolebinding-pod-readyonly
subjects:
- kind: ServiceAccount
  name: readonly-account
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: readonly-account-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: readonly-account
