name: CI/CD Pipeline with Kubernetes Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test app/./... -v

      - name: Build application
        run: go build -o sustainability-tool

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/sustainability-tool:${{ github.sha }} .

      - name: Push Docker image
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker push ghcr.io/${{ github.repository_owner }}/sustainability-tool:${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.2' # Use the desired kubectl version

      - name: Authenticate with Kubernetes cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/sustainability-tool \
          sustainability-tool=ghcr.io/${{ github.repository_owner }}/sustainability-tool:${{ github.sha }}
